Repository akhenry/openmct-yamcs, pull requests merged in 2024-09, with the labels that each got.

#473 build: use actual quickstart repo now that our changes are merged
  .github/workflows/yamcs-quickstart-e2e.yml
Labels: type:maintenance

#471 Deal with Parameter mdb overrides only
  src/utils.js
  tests/e2e/yamcs/load.e2e.spec.mjs
Labels: type:bug, bug:regression

#469 Test for Performance Mode changes incorrectly changing sort order
  tests/README.md
  tests/e2e/yamcs/telemetryTables.e2e.spec.mjs
Labels: type:maintenance

#482 Add makefile and build currentbranch npm scripting
  .gitignore
  Makefile
  package.json
Labels: type:maintenance

#470 Test to check that bar graph makes requests with size 1 (limit=1).
  Makefile
  example/index.js
  tests/README.md
  tests/e2e/yamcs/barGraph.e2e.spec.mjs
  tests/e2e/yamcsAppActions.mjs
Labels: type:bug

#477 Improved buffering
  example/index.js
  src/openmct-yamcs.js
  src/providers/realtime-provider.js
  tests/e2e/yamcs/realtimeData.e2e.spec.mjs
Labels: type:enhancement
